### ISSUE TITLE
The plug-in doesn't work with the latest redmine 6.0.1

### ISSUE THREAD

**Issue by muradurm** [HugoHasenbein/redmine_more_previews#107]

**Comment by kotashiratsuka** [comment]
The following errors

```
[31295] ! Unable to start worker
[31295] undefined local variable or method `unloadable' for module VinceLib::VObject::Constants::Defaults
[31295] /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:29:in `<module:Defaults>'
    /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:24:in `<module:Constants>'
    /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:23:in `<module:VObject>'
    /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:22:in `<module:VinceLib>'
    /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:21:in `<top (required)>'
    /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants.rb:22:in `require_relative'
    /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants.rb:22:in `<top (required)>'
    /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object.rb:22:in `require_relative'
    /home/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object.rb:22:in `<top (required)>'
    /home/redmine/plugins/redmine_more_previews/converters/vince/init.rb:27:in `require_relative'
    /home/redmine/plugins/redmine_more_previews/converters/vince/init.rb:27:in `<top (required)>'
    /home/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:33:in `load'
    /home/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:33:in `run_initializer'
    /home/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:112:in `each'
    /home/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:112:in `load'
    /home/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/converter.rb:204:in `load'
    /home/redmine/plugins/redmine_more_previews/init.rb:155:in `<top (required)>'
    /home/redmine/lib/redmine/plugin_loader.rb:31:in `load'
    /home/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
    /home/redmine/lib/redmine/plugin_loader.rb:61:in `each'
    /home/redmine/lib/redmine/plugin_loader.rb:61:in `block in load'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:407:in `instance_exec'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:407:in `block in make_lambda'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:179:in `block in call'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:668:in `block (2 levels) in default_terminator'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:667:in `catch'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:667:in `block in default_terminator'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:180:in `call'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:559:in `block in invoke_before'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:559:in `each'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:559:in `invoke_before'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:109:in `run_callbacks'
    /home/redmine/vendor/bundle/ruby/3.3/gems/activesupport-7.2.2/lib/active_support/reloader.rb:96:in `prepare!'
    /home/redmine/vendor/bundle/ruby/3.3/gems/railties-7.2.2/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
    /home/redmine/vendor/bundle/ruby/3.3/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `instance_exec'
    /home/redmine/vendor/bundle/ruby/3.3/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `run'
    /home/redmine/vendor/bundle/ruby/3.3/gems/railties-7.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
    /usr/local/lib/ruby/3.3/tsort.rb:231:in `block in tsort_each'
    /usr/local/lib/ruby/3.3/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
    /usr/local/lib/ruby/3.3/tsort.rb:434:in `each_strongly_connected_component_from'
    /usr/local/lib/ruby/3.3/tsort.rb:352:in `block in each_strongly_connected_component'
    /usr/local/lib/ruby/3.3/tsort.rb:350:in `each'
    /usr/local/lib/ruby/3.3/tsort.rb:350:in `call'
    /usr/local/lib/ruby/3.3/tsort.rb:350:in `each_strongly_connected_component'
    /usr/local/lib/ruby/3.3/tsort.rb:229:in `tsort_each'
    /usr/local/lib/ruby/3.3/tsort.rb:208:in `tsort_each'
    /home/redmine/vendor/bundle/ruby/3.3/gems/railties-7.2.2/lib/rails/initializable.rb:60:in `run_initializers'
    /home/redmine/vendor/bundle/ruby/3.3/gems/railties-7.2.2/lib/rails/application.rb:435:in `initialize!'
    /home/redmine/config/environment.rb:16:in `<top (required)>'
    config.ru:3:in `require_relative'
    config.ru:3:in `block (2 levels) in <top (required)>'
    /home/redmine/vendor/bundle/ruby/3.3/gems/rack-3.1.8/lib/rack/builder.rb:108:in `eval'
    /home/redmine/vendor/bundle/ruby/3.3/gems/rack-3.1.8/lib/rack/builder.rb:108:in `new_from_string'
    /home/redmine/vendor/bundle/ruby/3.3/gems/rack-3.1.8/lib/rack/builder.rb:97:in `load_file'
    /home/redmine/vendor/bundle/ruby/3.3/gems/rack-3.1.8/lib/rack/builder.rb:67:in `parse_file'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/configuration.rb:368:in `load_rackup'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/configuration.rb:290:in `app'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/runner.rb:173:in `app'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/runner.rb:177:in `start_server'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster/worker.rb:60:in `run'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster.rb:216:in `worker'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster.rb:97:in `block in spawn_worker'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster.rb:97:in `fork'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster.rb:97:in `spawn_worker'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster.rb:81:in `block in spawn_workers'
    <internal:numeric>:237:in `times'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster.rb:74:in `spawn_workers'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster.rb:173:in `check_workers'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cluster.rb:455:in `run'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/launcher.rb:194:in `run'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/lib/puma/cli.rb:75:in `run'
    /home/redmine/vendor/bundle/ruby/3.3/gems/puma-6.4.3/bin/puma:10:in `<top (required)>'
    /home/redmine/vendor/bundle/ruby/3.3/bin/puma:25:in `load'
    /home/redmine/vendor/bundle/ruby/3.3/bin/puma:25:in `<main>'
```

**Comment by muradurm** [comment]
The problem is described here: https://github.com/ruby-grape/grape/issues/2238#issuecomment-2407392147

> The method ActiveSupport::Dependencies.explicitly_unloadable_constants has been removed in Rails 7, which is why you're seeing a NoMethodError. This method was part of Rails' older autoloading system, but Rails 7 fully relies on the Zeitwerk autoloader, which does not use manually unloadable constants.
>
> To fix this, you need to migrate away from explicitly_unloadable_constants and rely on Zeitwerk’s autoloading, which handles reloading of constants automatically


I didn't test it much but the plug-in started to work after I've removed 'unloadable' in the following files:

converters/vince/lib/vince_lib/v_object/constants/defaults.rb
converters/vince/lib/vince_lib/v_object/modules/initializer.rb
converters/vince/lib/vince_lib/v_object/modules/escaping.rb
converters/vince/lib/vince_lib/v_object/modules/extraction.rb
converters/vince/lib/vince_lib/v_object/modules/filters.rb
converters/vince/lib/vince_lib/v_object/modules/localization.rb
converters/vince/lib/vince_lib/v_object/modules/setters.rb
converters/vince/lib/vince_lib/v_object/field_types/default.rb
converters/vince/lib/vince_lib/v_object/writer.rb
converters/vince/lib/vince_lib/v_object/reader.rb

and in the file plugins/redmine_more_previews/init.rb have removed the last line:
ActiveSupport::Dependencies.explicitly_unloadable_constants += ['RedmineMorePreviews']

**Comment by rohitnikharge26** [comment]
Where can I find all the above files in redmine?

**Comment by FloWalchs** [comment]
@HugoHasenbein 
Is this plugin planned for Redmine 6? or when do you think it will come, thank you

**Comment by tzoumara** [comment]
I installed it on 6.01 it works fine with @muradurm method. But it doesn't work on a 6.02 installation. I ended with an internal error and I couldn't even see the information tab in administration.

**Comment by muradurm** [comment]
> I installed it on 6.01 it works fine with [@muradurm](https://github.com/muradurm) method. But it doesn't work on a 6.02 installation. I ended with an internal error and I couldn't even see the information tab in administration.

It's claimed that "v5.0.8 now running on Redmine 6.0.x". But I've installed the latest v5.0.9 several days ago on Redmine v6.0.3 and still had to remove 'unloadable' from those files to have it working.

**Comment by jojo578578** [comment]
rake aborted!
NameError: undefined local variable or method `unloadable' for module VinceLib::VObject::Constants::Defaults (NameError)

      unloadable
      ^^^^^^^^^^
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:29:in `<module:Defaults>'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:24:in `<module:Constants>'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:23:in `<module:VObject>'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:22:in `<module:VinceLib>'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:21:in `<top (required)>'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants.rb:22:in `require_relative'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants.rb:22:in `<top (required)>'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object.rb:22:in `require_relative'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object.rb:22:in `<top (required)>'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/init.rb:27:in `require_relative'
/usr/src/redmine/plugins/redmine_more_previews/converters/vince/init.rb:27:in `<top (required)>'
/usr/src/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:33:in `load'
/usr/src/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:33:in `run_initializer'
/usr/src/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:112:in `each'
/usr/src/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:112:in `load'
/usr/src/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/converter.rb:204:in `load'
/usr/src/redmine/plugins/redmine_more_previews/init.rb:154:in `<top (required)>'
/usr/src/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/usr/src/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/usr/src/redmine/lib/redmine/plugin_loader.rb:61:in `each'
/usr/src/redmine/lib/redmine/plugin_loader.rb:61:in `block in load'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:407:in `instance_exec'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:407:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:179:in `block in call'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:668:in `block (2 levels) in default_terminator'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:667:in `catch'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:667:in `block in default_terminator'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:180:in `call'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:559:in `block in invoke_before'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:559:in `each'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:559:in `invoke_before'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/callbacks.rb:109:in `run_callbacks'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/reloader.rb:96:in `prepare!'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:435:in `initialize!'
/usr/src/redmine/config/environment.rb:16:in `<top (required)>'
/usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:411:in `require_environment!'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:559:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
-------------------------------------------------------------
my version is 6.0.3 ,when i installing the latest v5.0.9

**Comment by stefan-nu** [comment]
Same error on redmine 6.0.4 with ruby 3.1.2

ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]


<pre>
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NameError: undefined local variable or method `unloadable' for VinceLib::VObject::Constants::Defaults:Module

      unloadable
      ^^^^^^^^^^
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:29:in `<module:Defaults>'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:24:in `<module:Constants>'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:23:in `<module:VObject>'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:22:in `<module:VinceLib>'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants/defaults.rb:21:in `<top (required)>'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants.rb:22:in `require_relative'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object/constants.rb:22:in `<top (required)>'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object.rb:22:in `require_relative'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/lib/vince_lib/v_object.rb:22:in `<top (required)>'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/init.rb:27:in `require_relative'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/converters/vince/init.rb:27:in `<top (required)>'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:33:in `load'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:33:in `run_initializer'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:112:in `each'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/lib/redmine_more_previews/plugin_loader.rb:112:in `load'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/lib/redmine_more_previews/converter.rb:204:in `load'
/usr/local/redmine-6.0.4/plugins/redmine_more_previews/init.rb:154:in `<top (required)>'
/usr/local/redmine-6.0.4/lib/redmine/plugin_loader.rb:31:in `load'
/usr/local/redmine-6.0.4/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/usr/local/redmine-6.0.4/lib/redmine/plugin_loader.rb:61:in `each'
/usr/local/redmine-6.0.4/lib/redmine/plugin_loader.rb:61:in `block in load'
/usr/local/redmine-6.0.4/config/environment.rb:16:in `<top (required)>'
/usr/local/rbenv/versions/3.1.2/bin/bundle:25:in `load'
/usr/local/rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
</pre>

**Comment by stefan-nu** [comment]
I could compile the plugin by commenting all lines where only "unloadable" is stated.

I am not a ruby developer, so I do not know what this implies. From what I found on the web is that "unloadable" is a depreciated feature. 

I don't know if my approach breaks the plugin.

**Comment by dust2k** [comment]
After I removed all "unloadable", I can successfully install the plugin, but preview doesn't work, none of pdf, docx, xls and zip works at all, can't find any error either in nginx log or production.log...

**Comment by HugoHasenbein** [comment]
activate the plugin for the project in Project Configuration

**Comment by stefan-nu** [comment]
I activated the plugin in project configuration as you described. 

When I open a ticket with a pdf file attached, the pdf file does not get shown. Instead a black rectangle appears with an error message that states something like "error when loading pdf file". There is no corresponding error message in the log file though. 

<img width="1129" alt="Image" src="https://github.com/user-attachments/assets/83c81e4e-ea08-4303-b369-a4ecf8f56e38" />

**Comment by riros** [comment]
some problem. After installation preview not work
![1](https://portal.abinskcity.ru/assets/share/1.png)
![2](https://portal.abinskcity.ru/assets/share/2.png)
![3](https://portal.abinskcity.ru/assets/share/3.png)
![4](https://portal.abinskcity.ru/assets/share/4.png)

**Comment by cristian-spiescu** [comment]
I am curious: are there plans for an update so that the plugin runs smoothly on Redmine 6?

**Comment by camlafit** [comment]
Hi

To remove all _unloadable_ row you can do
```bash 
for file in $(grep -lir "\s*unloadable" converters/vince/lib/vince_lib/v_object/); do sed -i -e "s/\(\s*\)unloadable/\1#unloadable/" $file; done
```

init.rb  looks yet corrected
